#### REGISTER USER
POST http://localhost:5000/api/users/register
Content-Type: application/json

{
    "name": "Amani Mhinda",
    "email": "amanhhheeddsdfsfdiigggii2284228473.mhinda@gmail.com",
    "password": "plmpoi"
}